### ISSUE TITLE
Create app for qrp 

### ISSUE THREAD

**Issue by antonlalala** [jamesshao8/portapack-havoc-modified#1]
create an app for qrp, (cross "mictx and analog audio") add a mode for selecting the reception frequency and transmission frequency independently of each other, use the type of modulation and if possible add ssb. and power activation in case of transmission or constantly in the settings . thanks

**Comment by jamesshao8** [comment]
Hi, can you introduct what is mictx? And is there fun stuff to do with that app?  I am not a ham.

**Comment by antonlalala** [comment]
![1A43A90B-D999-4C31-B9BD-8335EA2969B1](https://user-images.githubusercontent.com/43932931/75158459-343d6000-5727-11ea-9219-cea73808e15d.jpeg)
![981334FF-19B8-4D9A-9C47-28590229BA32](https://user-images.githubusercontent.com/43932931/75158468-399aaa80-5727-11ea-89d2-9205838eda37.jpeg)
![25C71B9B-DE86-461A-8BBD-3D65E86C09EA](https://user-images.githubusercontent.com/43932931/75158469-3acbd780-5727-11ea-8c27-28b0b434ca94.jpeg)
![62744CD8-0D70-4DA8-89E5-F4226F9C7A79](https://user-images.githubusercontent.com/43932931/75158470-3b646e00-5727-11ea-8444-700f053668e3.jpeg)

**Comment by jamesshao8** [comment]
Thanks for your explanation. mictx stands for microphone transmit right? Combining it with analog audio, you will get something like a walkie-talkie. I have some friends who have similar request. I will see if I will have the time to achieve that. For the moment, I am busy writing analog video receiver for portapack.

**Comment by antonlalala** [comment]
Yes, that's right, thanks, I will expect. You post the updated release. bin ?

**Comment by antonlalala** [comment]
Hi, here is a visual example as we would like. you can make a second sheet with fine settings, such as microphone sensitivity, subton and others
![SCR_0005](https://user-images.githubusercontent.com/43932931/77353317-cbf79380-6d51-11ea-88ef-415410630119.jpg)

**Comment by jamesshao8** [comment]
Hi @antonlalala ,

Is there already a built-in microphone on your portapack or did you add it by yourself? I have a very old model has this mic, however the new ones dosen't have it. That's why I didn't make the software till today.

**Comment by antonlalala** [comment]
I planned to use the headset from the phone as in the "mic tx" program, but I can also solder the microphone. with a headset is more convenient if you add the function "vox". I am waiting for your software very much, and already starting to build an amplifier, I have a desire to work through satcom.

**Comment by jumbo77** [comment]
我也等你的软件，我做了一些H1，带电池充电，电池供电，适合作为对讲机。
i make some h1,with battery charge function,1 key power on /off ,ready for walkie talkie.
mic tx testing iphone headset ok.

**Comment by antonlalala** [comment]
@jumbo77  new pcb or...

**Comment by jamesshao8** [comment]
@antonlalala Thanks. I didn't know the headset on phone can be used as input. I confirmed it's working now. So I have the hardware ready. I will try to see if it possible to combine those 2 app.

**Comment by antonlalala** [comment]
Thanks, we will wait. important parameters: 1 modulation am, fm, lsb, usb. and bandwidth for both reception and transmission. can add ctss / dcstone.

**Comment by jamesshao8** [comment]
I have read the program yesterday. It seems difficult to realize a program with 2 direction of  the data ( receiving and transmitting). The best I can do is using a spare button to call mictx from analog_audio program.

**Comment by antonlalala** [comment]
come on so. and a quick call to the program analog audio from mic tx. But what about the modulation of the transmitter can be done am, fm, usb, lsb.

**Comment by antonlalala** [comment]
@jamesshao8 
Hi, anything new?

**Comment by jamesshao8** [comment]
Hi, I can't do a transceiver now. Because most of what I did is based on the modification of furttek's code. He has only implemented receivers or transimtters. There is no example of a transceiver.
