### ISSUE TITLE
NOAA RX

### ISSUE THREAD

**Issue by PeterDragonTM** [jamesshao8/portapack-havoc-modified#17]
Not an issue but more of a query. Did you ever get this NOAA RX App going, the one in the screen shot? I have a group of programmers who were looking to try something like this in another project. And I would love to know if you would be open to disclosing it on the repo?

**Comment by jamesshao8** [comment]
Yes, noaa rx is working. But I’m not interested in letting other people copy my code and take my credits.

**Comment by jLynx** [comment]
😂 😂 😂 😂 😂 But @jamesshao8 you stole other people's code and took credit for it.... Also you are in violation of the licence agreement. Hardware and software. You know this. You should be a stand up comedian as your response is hilarious 😂

**Comment by zxkmm** [comment]
Shame on you. 丢脸被你丢完了。
