### ISSUE TITLE
hackrf_sweep feature not supported by this firmware

### ISSUE THREAD

**Issue by madmystic** [jamesshao8/portapack-havoc-modified#20]
Hi,

When running: hackrf_sweep 

It tells me:

hackrf_start_rx_sweep() failed: feature not supported by installed firmware (-1005)

Is there any way to get hackrf_sweep to work? 

Thanks.

**Comment by jamesshao8** [comment]
What is the version of HackRF driver on your computer?
I am using 2018.01.1, which includes sweep and works fine for me.
