### ISSUE TITLE
`README.md`: URLs to sellers do not work.

### ISSUE THREAD

**Issue by dreirund** [jamesshao8/portapack-havoc-modified#25]
In your [`README.md`](https://github.com/jamesshao8/portapack-havoc-modified/blob/master/README.md?plain=1#L12..L19) you have URLs to sellers:

> ```markdown
> https://www.aliexpress.com/item/3256804550974838.html
> 
> 
> https://www.ebay.com/itm/XXX/115523402262
> 
> Swiftflying:
> 
> https://www.aliexpress.com/item/3256804545943517.html
> ```

All of those URLs do not work.

Regards!

**Comment by jamesshao8** [comment]
Thank you for pointing this out.

it seems the addresses are modified after a while.

I will adjust them soon.
