### ISSUE TITLE
No GPS sim app in Transmit 

### ISSUE THREAD

**Issue by qovtunov** [jamesshao8/portapack-havoc-modified#27]
I just install 1.3.0 version and there is no GPS sim app in Transmit apps. Is it removed from apps? If so, what firmware version still has it? Thanks.

**Comment by jamesshao8** [comment]
Hi, 

GPS sim is moved to some other places in latest firmware. You can find it in original position in v1.2.9.
If you want to try the latest firmware and still want to use GPS sim, please give me your email address, so I can send you a user manual.

**Comment by qovtunov** [comment]
It would be nice to have manual, thanks! 
beetstroop@gmail.com

**Comment by jamesshao8** [comment]
Hi, I have sent you an email with manual attached. @qovtunov

**Comment by qovtunov** [comment]
Sorry but I still can't find the app. As I understand in manual you say that it should be in Tx, but I don't have it. Should I install 1.3.1 maybe? @jamesshao8 
![photo_2024-05-07_11-10-14](https://github.com/jamesshao8/portapack-havoc-modified/assets/6003500/36f10785-1f1c-4206-8ab3-a9667458fd9d)
![photo_2024-05-07_11-10-01](https://github.com/jamesshao8/portapack-havoc-modified/assets/6003500/81464be9-e6ca-4c05-9424-42f55518a956)

**Comment by jamesshao8** [comment]
It's strange that I received your message in email. But can't see it here. I replied to you through email. Basically, you need a TF card (32GB, FAT32) inserted. And you can verify that by the icon on top-right corner.

**Comment by saviork** [comment]
Hi,send me too. thanks!
tianlang@gmail.com

**Comment by michaelbuud19** [comment]
Thanks
