### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by minkione** [jamesshao8/portapack-havoc-modified#3]
Hi, sorry for bothering on this repo, but I couldn't find another way to contact you.
I noticed you ran srsLTE on a LimeSDR.
Do you maybe have some notes about installation and configuration?

Thanks :)

**Comment by jamesshao8** [comment]
Yes I have notes on this topic. However it's written in Chinese. You can use google translator for that.
https://blog.csdn.net/shukebeta008/article/details/103515509

**Comment by minkione** [comment]
Thanks Sir!
Btw... the amount of good articles is impressive!
I wish I could read natively Chinese :)
