### ISSUE TITLE
Support for Capacitive Touchscreen?

### ISSUE THREAD

**Issue by RChadwick7** [jamesshao8/portapack-havoc-modified#6]
While looking for a replacement screen, I came across a Capacitive touch screen/LCD with apparently the same connector. WOuld it be possible to add support for the capacitive screen?

https://www.ebay.com/itm/Serial-SPI-3-2-TFT-LCD-Module-Display-ILI9341-w-Resistive-Touch-Panel-Tutorial-/291870027139

https://www.ebay.com/itm/Serial-SPI-3-2-TFT-LCD-Display-Module-ILI9341-w-Capacitive-Touch-Panel-Tutorial-/291870027141

**Comment by jamesshao8** [comment]
I am more familiar with software than hardware. I will ask  the manufacturer about that.
Can you update the ebay link? I cant see the page.

**Comment by RChadwick7** [comment]
I checked the schematics of the Portapack, HackRF, and the capacitive screen. The capacitive screen will fit, but won't function without cutting and rerouting 4 traces. It could be made to work, but it's not likely to happen.
